---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-config
data:
  CLIENT_TOTAL_REQUESTS: "16"
  CLIENT_TOTAL_FAILURE_RETRIES: "7"
  CLIENT_BACKOFF_FACTOR: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client-app
        image: sbouii/test-client:1.0
        envFrom:
          - configMapRef:
               name: client-config
