---
apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
data:
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  RATE_LIMIT: 10/10minute
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server-app
        image: sbouii/test-server:1.0
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
               name: server-config
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: server
